import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/navbar/header";
import NextAuthProvider from "@/providers/nextauth-provider";
import { AppContextProvider } from "@/context/app-context";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <NextAuthProvider>
          <AppContextProvider>
            {children}
          </AppContextProvider>
        </NextAuthProvider>
        <Toaster
          duration={2000}
          position="top-right"
          expand={false}
          closeButton
        />
      </body>
    </html>
  );
}
